# Generated by Django 5.2.8 on 2025-11-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'verbose_name_plural': 'Password Resets'},
        ),
        migrations.RenameField(
            model_name='passwordreset',
            old_name='uuid',
            new_name='reset_id',
        ),
    ]
